import { layout, csrfField, field } from './layout.js';
import { escapeHtml as e } from '../http.js';
export const loginPage = session => layout('Admin login', `<h2>Admin login :3</h2><form class="cms-form" action="/:3" method="post">${csrfField(session)}<label>Username<input name="username" autocomplete="username" required maxlength="200"></label><label>Password<input name="password" type="password" autocomplete="current-password" required maxlength="1024"></label><button>Log in</button></form>`, session);
export const dashboard = (session, counts) => layout('Dashboard', `<h2>Dashboard</h2><p>${counts.blogs} blog posts · ${counts.drawings} drawings · ${counts.uploads} images</p><p><a href="/admin/blogs/new">Write a blog</a> · <a href="/admin/drawings/new">Add a drawing</a> · <a href="/admin/uploads">Upload images</a></p>`, session);
export function editor(session, type, item = {}, uploads = []) {
  const blog = type === 'blogs';
  const action = `/admin/${type}/${item._id || 'new'}`;
  const buttons = ['b', 'i', 'u', 's', 'url', 'img', 'quote', 'code', 'list', 'center', 'color', 'size', 'video'].map(tag => `<button type="button" data-tag="${tag}">${tag}</button>`).join('');
  const upload = `<section><h3>Images</h3><label>Upload image (10 MiB maximum)<input type="file" id="image-upload" accept="image/jpeg,image/png,image/webp,image/gif"></label><p id="upload-status" role="status"></p><label>Image library<select id="image-library"><option value="">Select uploaded image</option>${uploads.map(f => `<option value="/uploads/${f._id}">${e(f.metadata?.originalName || f.filename)}</option>`).join('')}</select></label><button type="button" id="insert-image">${blog ? 'Insert image into post' : 'Use selected drawing image'}</button></section>`;
  return layout(item._id ? 'Edit' : 'Create', `<h2>${item._id ? 'Edit' : 'New'} ${blog ? 'blog' : 'drawing'}</h2><form method="post" action="${action}" class="cms-form" id="content-form" data-kind="${type}">${csrfField(session)}${field('title', item.title, 'text', true)}${blog ? field('slug', item.slug) : ''}${field('date', item.date || new Date().toISOString().slice(0, 10), 'date', true)}${blog ? `${field('coverImage', item.coverImage)}<div class="editor-toolbar">${buttons}</div><label>BBCode content<textarea name="content" id="bbcode" maxlength="200000" required>${e(item.content)}</textarea></label>` : `${field('image', item.image, 'text', true)}${field('thumbnail', item.thumbnail)}<label>Description<textarea name="description" maxlength="4000">${e(item.description)}</textarea></label>${field('order', item.order || 0, 'number')}`}${upload}<label><input type="checkbox" name="published" ${item.published ? 'checked' : ''}> Published (leave unchecked for a draft)</label><button>Save ${blog ? 'blog' : 'drawing'}</button>${blog ? ' <button type="button" id="preview-button">Preview</button>' : ''}<p id="editor-status" role="status"></p></form><iframe id="preview-frame" title="Post preview" sandbox="" hidden></iframe>`, session);
}
export function listPage(session, type, items, page, more) {
  return layout(type, `<h2>${e(type)}</h2><a href="/admin/${type}/new">Create ${type === 'blogs' ? 'blog' : 'drawing'}</a>${items.map(item => `<div class="cms-row"><strong>${e(item.title)}</strong> · ${e(item.date)} · ${item.published ? 'Published' : 'Draft'}<br><a href="/admin/${type}/${item._id}">Edit</a> · <a href="/admin/${type}/${item._id}/delete">Delete</a>${type === 'blogs' && item.published ? ` · <a href="/blog/${e(item.slug)}">View</a>` : ''}</div>`).join('')}${page > 1 ? `<a href="?page=${page - 1}">Previous</a>` : ''} ${more ? `<a href="?page=${page + 1}">Next</a>` : ''}`, session);
}
export const confirmDelete = (session, type, item) => layout('Confirm deletion', `<h2>Delete ${e(item.title || item.metadata?.originalName || 'image')}?</h2><p>${type === 'uploads' ? 'This removes the image from the upload library. Existing image URLs remain available so posts do not break.' : 'This removes the item from the public site and admin list. A recovery copy remains in the database.'}</p><form method="post">${csrfField(session)}<input name="confirm" type="hidden" value="delete"><button>Confirm delete</button> <a href="/admin/${type}">Cancel</a></form>`, session);
export function uploadsPage(session, files, page, more) {
  return layout('Uploads', `<h2>Uploads</h2><form id="upload-form">${csrfField(session)}<label>Choose an image (JPEG, PNG, WebP, GIF; max 10 MiB)<input type="file" id="image-upload" accept="image/jpeg,image/png,image/webp,image/gif"></label></form><p id="upload-status" role="status"></p>${files.map(f => `<div class="cms-row"><img src="/uploads/${f._id}" alt="${e(f.metadata?.originalName || '')}" loading="lazy"><p>${e(f.metadata?.originalName || f.filename)}</p><label>Image URL<input readonly value="/uploads/${f._id}"></label><a href="/admin/uploads/${f._id}/delete">Remove from library</a></div>`).join('')}${page > 1 ? `<a href="?page=${page - 1}">Previous</a>` : ''} ${more ? `<a href="?page=${page + 1}">Next</a>` : ''}`, session);
}
